import {field} from 'nodedata/mongoose/decorators';
import {Types} from 'mongoose';

export class BaseModel {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: String;
}

export default BaseModel;