import {onetomany, manytoone, manytomany} from 'nodedata/core/decorators';
import {field, document} from 'nodedata/mongoose/decorators';
import {Strict} from 'nodedata/mongoose/enums';

@document({ name: 'blogs', strict: Strict.true  })
export class BlogModel{
    @field({primary: true, autogenerated: true})
    _id: any;
    
    @field()
    name: any;
    
}
