import * as SM from './studentmodel';
import {onetomany, manytoone, manytomany} from 'nodedata/core/decorators';
import {field, document} from 'nodedata/mongoose/decorators';
import {Types} from 'mongoose';
import {Strict} from 'nodedata/mongoose/enums';

@document({ name: 'courses', strict: Strict.throw })
export class CourseModel {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: String;

    //@onetomany({ rel: 'teachers', biDirectional: true, itemType: TM, persist: true })
    //teachers: Array<TM.TeacherModel>;

    //@manytomany({rel: 'students', biDirectional: false, itemType: SM, persist: true})
    //students: Array<SM.StudentModel>;
}

export default CourseModel;